// Question 01

function addNum(num1){
    return function(num2){
        console.log(num1 + num2);
    }
}

const numberAdded = addNum(3);
numberAdded(5);

// Question 02

function recursiveSearch(arr, val, index = 0){
    if(index >= arr.length){
        return false;
    } else if(arr[index] === val){
        return true;
    } else{
        return recursiveSearch(arr, val, index + 1);
    }
}

const chkArr = [1,2,3,4];
console.log(recursiveSearch(chkArr, 2));
console.log(recursiveSearch(chkArr, 6));

// Question 03

function addParaHtml(text) {
    const newPara = document.createElement('p');
    const textPara = document.createTextNode(text);
    newPara.appendChild(textPara);
    document.body.appendChild(newPara);
}

addParaHtml("This paragraph is generated by JavaScript.");

// Question 04

function addNewListitem(text){
    const list = document.querySelector('ul');
    const newListItem = document.createElement('li');
    const listItemText = document.createTextNode(text);
    newListItem.appendChild(listItemText);
    list.appendChild(newListItem);
}

addNewListitem('Mango');

// Question 05

function chngeBackgrndClr(element, color) {
    element.style.backgroundColor = color;
}

const myHeading = document.getElementById('my-heading');
chngeBackgrndClr(myHeading, '#FECD50')

// Question 06

function saveToLocalStorage(key, object){
    let stringifyObject = JSON.stringify(object);
    localStorage.setItem(key, stringifyObject);
}

const car = {
    name: 'Supra',
    brand: 'Toyota',
    model: 2002,
    seatingCapacity: 2
}

saveToLocalStorage("favCar", car);

// Question 07

function retrieveObjFrmLocalStorage(key){
    let carObj = localStorage.getItem(key);
    return console.log(JSON.parse(carObj));
}

retrieveObjFrmLocalStorage("favCar");

// Question 08

function saveObjToLocStrge(obj){
    for (const [key, value] of Object.entries(obj)) {
        localStorage.setItem(key, JSON.stringify(value));
    }

    const newObj = {};
    for (let i = 0; i < localStorage.length; i++) {
        const key = localStorage.key(i);
        const value = JSON.parse(localStorage.getItem(key));
        newObj[key] = value;
    }
    return newObj;
}

const car1 = {
    name: 'Supra',
    brand: 'Toyota',
    model: 2002,
    seatingCapacity: 2
}

const retrieveObj = saveObjToLocStrge(car1);
console.log(retrieveObj);